# Introduction

By the late 1990s, concepts of risk and risk assessment were introduced as decision-making supports for the food safety managers. Modern food safety policies are intended to be risk-based [@koutsoumanis2016].The framework for carrying out risk assessments associated with foodborne pathogens (Microbiological Risk Assessment, MRA) is well established [@microbio2021] relying on four principal components including (i) hazard identification, (ii) hazard characterization, (iii) exposure assessment and (iv) risk characterization. This process involves including scientific data and studies in order to evaluate risks associated with different types of hazards. If the general MRA process is well structured, risk assessors can conduct qualitative and/or quantitative risk assessment methods (QMRA) while considering deterministic or stochastic methods as well as relevant uncertainties and variabilities. Hence, assessing the risks requires adequate data, metrics and modelling approaches depending on the QMRA components @fig-qmra.

```{mermaid}
%%| label: fig-qmra
%%| echo: false
%%| fig-cap: "Main components of QMRA frameworks"

graph TD
Q[Risk question]
H[Hazards]
PM[Product/Matrix]
P[Population group]
DR[Dose-response model]
PrM[Process model]
CM[Consumption model]
E[Exposure model]
HM[Health metrics]
R[Risk characterization model]



subgraph Hazard identification
Q-->H
Q-->PM
Q-->P
end

subgraph Exposure assessment
H-->PrM
PM-->PrM
PM-->CM
P-->CM
PrM-->E
CM-->E
end

subgraph Hazard characteryzation
H-->DR
P-->DR
end

subgraph Risk characterization
H-->HM
DR-->R
HM-->R
E-->R
end

```

The QMRA approach can help to answer various questions. For examples, [@jdom_2022] identified the following objectives:

-   evaluation of illness risk,

-   assessment of interventions,

-   simple exposure assessment,

-   or risk ranking.

Each objective is associated with specific starting points (farm, food industry, retail, etc.), output measurements (score or risk, mean annual risk, number of clinical cases, Disability Adjusted Life Year

DALY, etc.) and data needs.

One of the main challenge is to identify the appropriate approach to tackle the risk question. In this context, EJP OH COHESIVE proposes a decision support tool to help risk assessors ([COHESIVE Decision Support Tool](https://rawcdn.githack.com/RDewar/Decision-support-tool-EJP/c369a4f897ed09ef9c8b6e6fbc58d42014a298bf/Workingtool1.html)) to define the best approach according to the objective and the available time.

Once the approach has been chosen, different types of data can be collected (microbial concentrations, daily consumption, etc.) or gathered from different sources. The collected data should be fit for purpose, representative and allow a meaningful analysis [@Haberbeck2018]. as suggested from guidelines by FAO WHO (2021), the required type of data as well as the collection source can vary depending on the risk assessment components (Table ...).

Table...; Data required for risk assessment and data collection sources ([@microbio2021])

+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Type of data                                                                             | Description                                                                                                                                                                                  | Collection source                                                              |
+:=========================================================================================+:=============================================================================================================================================================================================+:===============================================================================+
| **Hazard identifcation**                                                                 |                                                                                                                                                                                              |                                                                                |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| association between exposure and adverse health oucome                                   | the evidence that can be utilized to pair the food and microbiological hazard and link the exposure to hazard in specific food to human illnesses                                            | -   Outbreak data                                                              |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Foodborne disease surveillance and annual health statistic                 |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Food safety rapid alert systems                                            |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Literature: Analytical epidemiological studies                             |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Systematic food contamination monitoring surveys                           |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Microbiological hazard characteristics                                                   | Characteristics of the organisms and mechanism with which the organism affects the host are described, while detailed dose - response analysis is done in hazard caharacterization           | -   Literature: Microbiological studies                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| General characteristics of food and conditions of supply chain                           | Intrinsic characteristics of the food (e.g. pH, water activity) and process evaluation (e.g. time, temperature)                                                                              | -   Industry data and literature: Description of product and food supply chain |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Adverse health outcome in exposed population                                             | Disease and sequalae in population and subpopulations by demographic and/or social-economic factors, sensitive population                                                                    | -   Scientific and medical literature                                          |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| **Exposure Assessment**                                                                  |                                                                                                                                                                                              |                                                                                |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Prevalence and concentration                                                             | Data on prevalence and concentration of the hazard in the food at the starting point of the risk assessment and other points of the food chain                                               | -   Systematic food contamination monitoring surveys                           |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Literature: prevalence and concentration surveys                           |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Expert Knowledge Elicitation (EKE)                                         |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Processing condition                                                                     | Data describing the conditions of food processing which may affect prevalence and concentration of the hazard, i.e. time-temperature of thermal processing, fermentation, partitioning, etc. | -   Literature and industry data: Description of products and supply chain     |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Effect of the processing stages and/or interventions                                     | Data on the effect of a processing stage/intervention on prevalence and concentration of the hazard                                                                                          | -   Literature: Intervention studies                                           |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Product chracteristics                                                                   | Data on food characteristics (p\                                                                                                                                                             | -   Literature and Industry data: Description of product and supply chain      |
|                                                                                          | H, awn concentration of antimicrobials, packaging atmosphere, use-by-date, etc.) that may affect the behaviour of the hazard during storage                                                  |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Distribution and storage conditions                                                      | Time-temperature data for distribution and storage of the food at retail and domestic level                                                                                                  | -   Literature and Industry data: Description of the product and supply chain  |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| condition of food handing and preparation                                                | Data describing the conditions of food handing and preparation which may affect prevalence and concentration of the hazard, i.e. time and temperature of cooking, partitioning, etc.         | -   Literature: Cross-contamination, food handing and preparation              |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Kinetic of hazard's behavior                                                             | Data on the kinetics of hazard's growth/survival/inactivation during food processing, distribution, storage, handing and cooking                                                             | -   Literature: Predictive microbiology models                                 |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Online modelling tools                                                     |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Consumption                                                                              | Data on serving size, frequency of consumption, and number of annual serving for different population groups (normal, susceptible, etc.)                                                     | -   National consumption database                                              |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Total diet studies                                                         |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   EKE                                                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Population segments                                                                      | Data on population size by segments                                                                                                                                                          | National population census                                                     |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Annual production of thhe food commodity                                                 | Data on amount of food produced in a country and information of imports and exports, if necessary                                                                                            | National food production statistics                                            |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| **Hazard characterization**                                                              |                                                                                                                                                                                              |                                                                                |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Doise-response data                                                                      | Dose-response data that can be used in fitting a dose-response model                                                                                                                         | Outbreak data - Volunteer feeding studies - Animal studies                     |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Parameters of dose-response models                                                       | Parameters estimated by fitting a dose-response model to data                                                                                                                                | Literature: fitted dose-response models                                        |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Annual cases of the foodborne illness and prevalence of the pathogen in a food commodity | Data on reported cases of illness and prevalence of the causative hazard in the food commodity to validate dose-response relationship                                                        | -   Foodborne disease surveillance and annual health statistics                |
|                                                                                          |                                                                                                                                                                                              |                                                                                |
|                                                                                          |                                                                                                                                                                                              | -   Systematic monitoring surveys                                              |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| **Risk characterization**                                                                |                                                                                                                                                                                              |                                                                                |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| Annual cases of foodborne illness                                                        | Data used for anchoring and/or validate a risk assessment model                                                                                                                              | -   Fooborne disease surveillance and annual health statistics                 |
+------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+

::: callout-note
## Objective of this document

Our goal is to provide a help to identify data/knowledge that risk assessors and data scientists need at the start of their projects.
:::

::: callout-caution
## Versioning of the document

This is the first release (September 2022) of the "Guide for accessing relevant data and models for quantitative microbial risk assessment". The document is uploaded in Zenodo, latest release can be find here: . This document will be maintained by authors according to the sustainability plan of CARE. All stakeholders, including students, researchers,risk assessment teams, are encouraged to use this document. Any feedback and improvement suggestion from the users is welcome so to make this guide a useful tool for everyone.
:::
